services:
  - type: web
    name: crypto-lstm-server
    runtime: python
    pythonVersion: 3.12
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --workers=1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120

jobs:
  - type: cron
    name: crypto-lstm-signal-job
    schedule: "*/5 * * * *"
    runtime: python
    pythonVersion: 3.12
    buildCommand: pip install -r requirements.txt
    startCommand: python signals.py
