services:
  - type: web
    name: crypto-lstm-server
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 120

jobs:
  - type: cron
    name: crypto-lstm-signal-job
    schedule: "*/5 * * * *"
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python signals.py
