services:
  - type: web
    name: crypto-lstm-server
    env: PYTHON_VERSION: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 120

jobs:
  - type: cron
    name: crypto-lstm-signal-job
    schedule: "*/5 * * * *"
    env: PYTHON_VERSION: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: python signals.py
