services:
  - type: web
    name: crypto-lstm-server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 120

jobs:
  - type: cron
    name: crypto-lstm-signal-job
    schedule: "*/5 * * * *"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: python signals.py
