services:
  - type: web
    name: crypto-lstm-server
    runtime: python3.12
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 120

jobs:
  - type: cron
    name: crypto-lstm-signal-job
    schedule: "*/5 * * * *"
    runtime: python3.12
    buildCommand: pip install -r requirements.txt
    startCommand: python signals.py
